### ISSUE TITLE
Download more files than announced

### ISSUE THREAD

**Issue by mlep** [llauner/AirspaceDownloader#2]
The readme.md states that the following file are downloaded:

- https://planeur-net.github.io/airspace/france.txt
- https://planeur-net.github.io/outlanding/guide_aires_securite.cup
- https://planeur-net.github.io/outlanding/champs_des_alpes.cup
- https://planeur-net.github.io/outlanding/cols_des_alpes.cup

In fact, additional files are downloaded too:

- Ludo_waypoints.cup
- mountain_peaks_IT.cup
- mountain_peaks_FR.cup
- mountain_peaks_CH.cup

**Comment by llauner** [comment]
List updated
